.TH ALIGN 1 2024-08-05 "align 0.0.1"

.SH NAME
align \- text alignment utility

.SH SYNOPSIS
.B align
[\fB-sep <seperator>\fR]

.SH OPTIONS
.TP
.BR \-sep " " \fIseperator
specifies the seperator used for aligning text.

.SH DESCRIPTION
Aligns FILE or standard input.

.SH EXAMPLES
.TP
.B align \fR\-sep \fR"="\fR < \fIfoo.txt
aligns the foo.txt FILE then print it onto standard output.
.TP
.B echo \fR"UNAME = uname\enPWD = pwd" | \fBalign \fR\-sep \fR"="\fR
uses \fBecho\fR(1) to supply foo.txt into standard input.

.SH SEE ALSO
\fBcolumn\fR(1)
